export const CHANGE_ID_INSTANCE = 'CHANGE_ID_INSTANCE';
export const CHANGE_TOKEN_FIELD = 'CHANGE_TOKEN_FIELD';
export const CHANGE_CHAT_ID = 'CHANGE_CHAT_ID';
export const CHANGE_TEXTAREA_FIELD = 'CHANGE_TEXTAREA_FIELD';
export const SET_ANSWER = 'SET_ANSWER'